env_proj.sh ran
PWD is [/home/patrick/client/ccg/cvms_pg]
DB_CONT is [cvms_db_cont]
DB_IMG is  [cvms_db_img]
DB_PORT_INT is  [5432]
DB_PORT_EXT is  [5432]
POSTGRES_DBNAME is [cvms]
POSTGRES_PASSWORD is  [cvms]
POSTGRES_USERNAME is  [cvms]
Error response from daemon: No such container: cvms_db_cont
Error: No such container: cvms_db_img
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2020-08-27 17:40:31.457 UTC [46] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-08-27 17:40:31.460 UTC [46] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-27 17:40:31.490 UTC [47] LOG:  database system was shut down at 2020-08-27 17:40:31 UTC
2020-08-27 17:40:31.497 UTC [46] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.sql
CREATE DATABASE
CREATE ROLE
GRANT


2020-08-27 17:40:31.713 UTC [46] LOG:  received fast shutdown request
waiting for server to shut down....2020-08-27 17:40:31.716 UTC [46] LOG:  aborting any active transactions
2020-08-27 17:40:31.720 UTC [46] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
2020-08-27 17:40:31.720 UTC [48] LOG:  shutting down
2020-08-27 17:40:31.755 UTC [46] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2020-08-27 17:40:31.851 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-08-27 17:40:31.851 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-27 17:40:31.851 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-08-27 17:40:31.857 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-27 17:40:31.898 UTC [64] LOG:  database system was shut down at 2020-08-27 17:40:31 UTC
2020-08-27 17:40:31.906 UTC [1] LOG:  database system is ready to accept connections
2020-08-27 18:43:24.672 UTC [270] ERROR:  type "datetime" does not exist at character 63
2020-08-27 18:43:24.672 UTC [270] STATEMENT:  create table location (location_id int8 not null, last_update DATETIME(3), latitude float8, location_type varchar(255), longitude float8, obj_code varchar(255), prim_lang_name varchar(255), rank int8, seco_lang_name varchar(255), primary key (location_id))
2020-08-27 18:43:24.775 UTC [270] ERROR:  syntax error at or near "user" at character 14
2020-08-27 18:43:24.775 UTC [270] STATEMENT:  create table user (user_id  bigserial not null, email varchar(255), first_name varchar(255), fleet_id int8, last_name varchar(255), organisation varchar(255), password varchar(255) not null, role varchar(255) not null, user_name varchar(255), user_role_id int8, primary key (user_id))
2020-08-27 18:43:24.907 UTC [270] ERROR:  relation "location" does not exist
2020-08-27 18:43:24.907 UTC [270] STATEMENT:  alter table if exists traffic_event add constraint FKlh5gais6dt5oaoms40h86dq5q foreign key (location_id) references location
2020-08-27 18:55:44.725 UTC [335] ERROR:  type "datetime" does not exist at character 63
2020-08-27 18:55:44.725 UTC [335] STATEMENT:  create table location (location_id int8 not null, last_update DATETIME(3), latitude float8, location_type varchar(255), longitude float8, obj_code varchar(255), prim_lang_name varchar(255), rank int8, seco_lang_name varchar(255), primary key (location_id))
2020-08-27 18:55:44.731 UTC [335] ERROR:  syntax error at or near "user" at character 14
2020-08-27 18:55:44.731 UTC [335] STATEMENT:  create table user (user_id  bigserial not null, email varchar(255), first_name varchar(255), fleet_id int8, last_name varchar(255), organisation varchar(255), password varchar(255) not null, role varchar(255) not null, user_name varchar(255), user_role_id int8, primary key (user_id))
2020-08-27 18:55:44.849 UTC [335] ERROR:  relation "location" does not exist
2020-08-27 18:55:44.849 UTC [335] STATEMENT:  alter table if exists traffic_event add constraint FKlh5gais6dt5oaoms40h86dq5q foreign key (location_id) references location
2020-08-28 12:21:45.649 UTC [1959] ERROR:  type "datetime" does not exist at character 63
2020-08-28 12:21:45.649 UTC [1959] STATEMENT:  create table location (location_id int8 not null, last_update DATETIME(3), latitude float8, location_type varchar(255), longitude float8, obj_code varchar(255), prim_lang_name varchar(255), rank int8, seco_lang_name varchar(255), primary key (location_id))
2020-08-28 12:21:45.654 UTC [1959] ERROR:  syntax error at or near "user" at character 14
2020-08-28 12:21:45.654 UTC [1959] STATEMENT:  create table user (user_id  bigserial not null, email varchar(255), first_name varchar(255), fleet_id int8, last_name varchar(255), organisation varchar(255), password varchar(255) not null, role varchar(255) not null, user_name varchar(255), user_role_id int8, primary key (user_id))
2020-08-28 12:21:45.749 UTC [1959] ERROR:  relation "location" does not exist
2020-08-28 12:21:45.749 UTC [1959] STATEMENT:  alter table if exists traffic_event add constraint FKlh5gais6dt5oaoms40h86dq5q foreign key (location_id) references location
DB^C2020-08-28 16:57:16.528 UTC [1] LOG:  received fast shutdown request
2020-08-28 16:57:16.533 UTC [1] LOG:  aborting any active transactions
2020-08-28 16:57:16.534 UTC [83] FATAL:  terminating connection due to administrator command
2020-08-28 16:57:16.539 UTC [1] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
2020-08-28 16:57:16.542 UTC [65] LOG:  shutting down
2020-08-28 16:57:16.572 UTC [1] LOG:  database system is shut down
patrick@spectre:~/client/ccg/cvms_pg$ ./linux.sh
linux.sh ran
patrick@spectre:~/client/ccg/cvms_pg$ ./kill.sh
env_proj.sh ran
DB_CONT   is [cvms_db_cont]
cvms_db_cont
env_proj.sh ran
DB_IMG is  [cvms_db_img]
DB_CONT is [cvms_db_cont]
cvms_db_cont
Untagged: cvms_db_img:latest
Deleted: sha256:889451dbbec86ef68c8b265583f6b3e6c1b325573903a95794c095e5e2d9baee
Deleted: sha256:905c7d8cbd5815a934dd0e04f9d49fc97ba52b914b94c9a4df2e3ad77b740263
Deleted: sha256:7f609588ca77fdeb7506095c51da655b7db10b661fc3491001111631b466a254
patrick@spectre:~/client/ccg/cvms_pg$ ./build.sh
env_proj.sh ran
PWD is [/home/patrick/client/ccg/cvms_pg]
DB_IMG is [cvms_db_img]
Sending build context to Docker daemon  348.2kB
Step 1/3 : FROM postgres:12
 ---> 62473370e7ee
Step 2/3 : EXPOSE 5432
 ---> Running in ea7f8cc56b76
Removing intermediate container ea7f8cc56b76
 ---> de1229b4eb64
Step 3/3 : COPY ./scripts/db/schema.sql /docker-entrypoint-initdb.d/
 ---> bcc81aa2289b
Successfully built bcc81aa2289b
Successfully tagged cvms_db_img:latest
patrick@spectre:~/client/ccg/cvms_pg$ ./run.sh
env_proj.sh ran
PWD is [/home/patrick/client/ccg/cvms_pg]
DB_CONT is [cvms_db_cont]
DB_IMG is  [cvms_db_img]
DB_PORT_INT is  [5432]
DB_PORT_EXT is  [5432]
POSTGRES_DBNAME is [cvms]
POSTGRES_PASSWORD is  [cvms]
POSTGRES_USERNAME is  [cvms]
Error response from daemon: No such container: cvms_db_cont
Error: No such container: cvms_db_img
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2020-08-28 16:57:35.428 UTC [47] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-08-28 16:57:35.432 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-28 16:57:35.457 UTC [48] LOG:  database system was shut down at 2020-08-28 16:57:35 UTC
2020-08-28 16:57:35.464 UTC [47] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/schema.sql
CREATE DATABASE
CREATE ROLE
GRANT


2020-08-28 16:57:35.700 UTC [47] LOG:  received fast shutdown request
waiting for server to shut down....2020-08-28 16:57:35.702 UTC [47] LOG:  aborting any active transactions
2020-08-28 16:57:35.703 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2020-08-28 16:57:35.704 UTC [49] LOG:  shutting down
2020-08-28 16:57:35.730 UTC [47] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2020-08-28 16:57:35.836 UTC [1] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2020-08-28 16:57:35.837 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-08-28 16:57:35.837 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2020-08-28 16:57:35.842 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-08-28 16:57:35.865 UTC [65] LOG:  database system was shut down at 2020-08-28 16:57:35 UTC
2020-08-28 16:57:35.871 UTC [1] LOG:  database system is ready to accept connections

